Dev 9988 support buildah
AccessibleAI/cnvrg-operator pull request #16
Opened 2021-12-02 14:16 UTC by TomerHasson

2021-12-05 10:31 UTC, Dimss requested changes

2021-12-05 10:31 UTC, Dimss commented on pkg/controlplane/tmpl/conf/rbac/buildimage-job-role.tpl
> +{{- if not .Spec.ControlPlane.BaseConfig.CnvrgJobRbacStrict }}
remove rules, we don't need it here

2021-12-05 10:31 UTC, Dimss commented on pkg/controlplane/tmpl/conf/cm/config-base.tpl
> +  CRI: "{{ .Spec.Cri }}"
Rename `CRI` to `CNVRG_CRI`

2021-12-05 11:08 UTC, TomerHasson commented on pkg/controlplane/tmpl/conf/rbac/buildimage-job-role.tpl
> +{{- if not .Spec.ControlPlane.BaseConfig.CnvrgJobRbacStrict }}
fixed

2021-12-06 09:59 UTC, Dimss requested changes

2021-12-06 09:59 UTC, Dimss commented on controllers/utils.go
> +		return "", err
handle error correctly -> require reconcile on error

2021-12-06 09:59 UTC, Dimss commented on controllers/utils.go
> +	if strings.Contains(cri, string(mlopsv1.CriTypeContainerd)) {
we need explicitly support for all cris 
if we are not able to detect the cri -> fall into the error state 
supported cris are:
docker
containerd
cri-o

2021-12-06 10:24 UTC, Dimss approved these changes
looks good

2021-12-06 10:24 UTC, Dimss commented on controllers/cnvrginfra_controller.go
> +	default:
remove the default

2021-12-06 10:24 UTC, Dimss commented on pkg/logging/tmpl/fluentbit/cm.tpl
>    {{ $app.SpecName }}-{{ $app.SpecNs }}-input.conf: |
use global scope `$.`

2021-12-06 10:25 UTC, Dimss submitted a review, later dismissed

2021-12-07 09:10 UTC, Dimss submitted a review, later dismissed
look good

2021-12-16 07:41 UTC, Dimss approved these changes

2021-12-16 07:41 UTC, merged