Dev 12639 es indices
AccessibleAI/cnvrg-operator pull request #41
Opened 2022-03-02 09:49 UTC by IsraelMurciano

2022-03-02 10:54 UTC, Dimss requested changes

2022-03-02 10:54 UTC, Dimss commented on config/crd/bases/mlops.cnvrg.io_cnvrgapps.yaml
> +                    cnvrgPrivilegedJob:
merge into your branch latest main

2022-03-02 10:54 UTC, Dimss commented on chart/crds/mlops.cnvrg.io_cnvrgapps.yaml
> +                    cnvrgPrivilegedJob:
this has been removed from main, merge main into your branch

2022-03-02 10:54 UTC, Dimss commented on pkg/controlplane/tmpl/crds/mlops.cnvrg.io_cnvrgapps.yaml
> +                    cnvrgPrivilegedJob:
merge into your branch latest main

2022-03-02 12:33 UTC, Dimss approved these changes

2022-03-02 12:37 UTC, merged

2022-03-13 09:14 UTC, itayariel commented on pkg/controlplane/tmpl/webapp/dep.tpl
> +        - name: "CNVRG_ENDPOINTS_INDEX"
@IsraelMurciano this env is only getting into the app pod and not to any of the sidekiq pods
reopening issue, please fix, maybe use one of the configmaps that are mounted to those pods