Dev 14218 add cnvrg app cnvrg infra api for east west
AccessibleAI/cnvrg-operator pull request #73
Opened 2022-06-08 06:11 UTC by MrEsL

2022-06-08 10:16 UTC, Dimss requested changes
@MrEsL

2022-06-08 10:16 UTC, Dimss commented on pkg/dbs/tmpl/es/sts.tpl
> +        {{- if and (.Spec.Networking.EastWest.Enabled) (not .Spec.Networking.EastWest.Primary) }}
the `sidecar.istio.io/inject: "true"`, are we planning to manually manage the sidecar injection?

2022-06-08 10:16 UTC, Dimss commented on pkg/logging/tmpl/elastalert/ingress.tpl
> +apiVersion: networking.k8s.io/v1beta1
why do we've an ingress for elastalert? is it something new?

2022-06-09 09:29 UTC, MrEsL commented on pkg/logging/tmpl/elastalert/ingress.tpl
> +apiVersion: networking.k8s.io/v1beta1
I just saw there was vs for elastalert so didnt see a reason for there not to be ingress aswell

2022-06-09 09:30 UTC, MrEsL commented on pkg/dbs/tmpl/es/sts.tpl
> +        {{- if and (.Spec.Networking.EastWest.Enabled) (not .Spec.Networking.EastWest.Primary) }}
not sure I understand? the annnotation causes mutation with automatic sidecar

2022-06-09 09:33 UTC, MrEsL commented on api/v1/networking.go
> +	EastWest              EastWest          `json:"eastWest,omitempty"`
in cnvrgapp there is not istio struct, so eastwest is under networking. (eastwest is not under ingress?)
in cnvrginfra eastwest is under istio.

2022-06-20 10:31 UTC, Dimss reviewed
so far looks good , 
please add tests, 
good job! 
you are the True developer! 
Fucking Golang Cloud Native Developer! 
Ask for 50k :)

2022-06-21 01:33 UTC, closed without merging